apiVersion: v1
entries:
  elasticsearch:
  - apiVersion: v1
    appVersion: 7.17.3
    created: "2023-08-24T09:19:57.8646643+08:00"
    description: Official Elastic helm chart for Elasticsearch
    digest: 437a6bd248482b8eb663a1f63bee6c2f9d00c0d77abe90c5a86ca35631969608
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/elasticsearch.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: elasticsearch
    sources:
    - https://github.com/elastic/elasticsearch
    urls:
    - https://github.com/nejinn/sky-walking-helm/blob/main/skywalking-helm-4.5.0/chart/skywalking/charts/elasticsearch-7.17.3.tgz
    version: 7.17.3
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 15.1.0
    created: "2023-08-24T09:19:57.8676655+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 6706df44c06603a6e43d8ff250e5587e2d9223518259825d73ba4f98b1ef0ea7
    home: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/containers/tree/main/bitnami/postgresql
    - https://www.postgresql.org/
    urls:
    - https://github.com/nejinn/sky-walking-helm/blob/main/skywalking-helm-4.5.0/chart/skywalking/charts/postgresql-12.1.2.tgz
    version: 12.1.2
  skywalking-helm:
  - apiVersion: v2
    created: "2023-08-24T09:19:57.8627523+08:00"
    dependencies:
    - condition: elasticsearch.enabled
      name: elasticsearch
      repository: https://helm.elastic.co/
      version: ~7.17.1
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.2
    description: Helm Chart for Apache SkyWalking
    digest: 07e484dad54258a70d4a7de9b9d7a38f1a6142f63b00317b1f84c53d3b3c816f
    home: https://skywalking.apache.org
    icon: https://raw.githubusercontent.com/apache/skywalking-kubernetes/master/logo/sw-logo-for-chart.jpg
    maintainers:
    - email: hanahmily@gmail.com
      name: hanahmily
    - email: innerpeace.zhai@gmail.com
      name: innerpeacez
    - email: kezhenxu94@163.com
      name: kezhenxu94
    name: skywalking-helm
    sources:
    - https://github.com/apache/skywalking-kubernetes
    urls:
    - https://github.com/nejinn/sky-walking-helm/blob/main/skywalking-helm-4.5.0/chart/skywalking/skywalking-helm-4.5.0.tgz
    version: 4.5.0
generated: "2023-08-24T09:19:57.8559964+08:00"
